import Head from "next/head";
import Link from "next/link";
import React, { FunctionComponent, ReactNode } from "react";

interface Props {
  children: ReactNode;
}

const Layout: FunctionComponent<Props> = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/aktuellt">
          <a>Aktuellt</a>
        </Link>
        <div>
          <Link href="/deltavlingar">
            <a>Deltävlingar</a>
          </Link>
          <ul>
            <li>Tävlingar lista</li>
          </ul>
        </div>
        <Link href="/arslista">
          <a>Årslista</a>
        </Link>
        <Link href="/deltagare">
          <a>Deltagare</a>
        </Link>
        <Link href="/">
          <a>Hem (LOGO)</a>
        </Link>
        <Link href="/statistik">
          <a>Statistik</a>
        </Link>
        <Link href="/galleri">
          <a>Galleri</a>
        </Link>
        <Link href="/om-touren">
          <a>Om Touren</a>
        </Link>
      </header>

      <main>
        <br />
        <br />
        {children}
        <br />
        <br />
      </main>

      <footer>Footer</footer>
    </div>
  );
};

export default Layout;
