import type { NextPage } from "next";
import Head from "next/head";
import { createClient } from "next-sanity";

export const client = createClient({
  projectId: "p2jab1yc",
  dataset: "production",
  apiVersion: "2022-10-21",
  useCdn: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Header</header>

      <main></main>

      <footer>Footer</footer>
    </div>
  );
};

export default Home;
